name: "continuous-integration"
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jorelali/setup-elm@v2
        with:
          elm-version: 0.19.1
      - run: node -v
      - run: npm install
      - run: elm-format src/ --validate
      - run: npm run-script build
